### ISSUE TITLE
How to clean up repeated documents

### ISSUE THREAD

**Issue by MichaelSowah** [marioreggiori/objectdb#17]
Is there a method to clean up repeated documents?

**Comment by stemuk** [comment]
@MichaelSowah The easiest way to achieve this if I understand you correctly is by just using the standart `db.remove` functionality. This would allow you to go like 
```
db.remove(
{
 'index': 'hello',
}
)
```
if `'index': 'hello',` is a similar aspect of all the repeated documents. Just use one similarity and then use the `db.remove` method to clean up the similar documents.

**Comment by marioreggiori** [comment]
I don't understand what you're trying to do. Can you give an equivalent example in SQL for what you trying to achieve?
