### ISSUE TITLE
Deletion Error

### ISSUE THREAD

**Issue by fritz-playmaker** [marioreggiori/objectdb#19]
![image](https://user-images.githubusercontent.com/13557612/50573429-c23fe400-0dcb-11e9-8bca-1fd067d7ed42.png)
Trying to delete the database but i get an error i believe is from ObjectDB's end.

This is my code for deletion.

```
 Future deleteCapturedData(String projectId) async {
     Directory appDocDir = await getApplicationDocumentsDirectory();
    String dbFilePath = appDocDir.path + "/op_" + projectId + ".data";
    var db = ObjectDB(dbFilePath);
    db.open();
    await db.remove({});
    await db.close();
  }
```

The error is in the attached picture
![](https://files.slack.com/files-pri/T6JAEQZFA-FF3G3BJUQ/image.png)

**Comment by marioreggiori** [comment]
Your code doesn't match the path in the error message. Are you sure that you don't try to delete the backup file somewhere else in your code?

**Comment by fritz-playmaker** [comment]
no please. I am not deleting any backup file. I noticed that when I used the `db.remove()` function and then subsequently accessed the db, i get the above error.  I also got the error after inserting into the db, and then subsequently trying to read data afterwards

**Comment by alexelisenko** [comment]
I am having the same issue, @marioreggiori any clues as to why this is happening?

**Comment by marioreggiori** [comment]
@alexelisenko unfortunately I could not reproduce this error.
Can you provide a full example (code) with additional information like Flutter version?

**Comment by alexelisenko** [comment]
I was actually able to get around this issue by doing `db.open(true);` to stop the "tidy" method from being called.

**Comment by marioreggiori** [comment]
Do you use objectdb with dart only or inside the flutter environment.
I think it is a problem caused by file permission. 
It would be nice if you could provide further information.

**Comment by marioreggiori** [comment]
Please reopen and provide some information if this still happens.
