### ISSUE TITLE
FileSystemException: Cannot delete file, path..... when adding data to DB

### ISSUE THREAD

**Issue by fritz-playmaker** [marioreggiori/objectdb#20]
Cant seem to add data to my DB. I get the error

`FileSystemException: Cannot delete file, path = '/data/user/0/com.thePlay/app_flutter/expenses.data.bak' (OS Error: No such file or directory, errno = 2)

File._delete.<anonymous closure> (dart:io/file_impl.dart:295:9)
RootZone.runUnary (dart:async/zone.dart:1379:54)
FutureListener.handleValue (dart:async/future_impl.dart:129:18)
Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
Future._propagateToListeners (dart:async/future_impl.dart:671:32)
Future._completeWithValue (dart:async/future_impl.dart:486:5)
Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
_microtaskLoop (dart:async/schedule_microtask.dart:41:21) _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`

**Comment by alaindixon** [comment]
same issue :(

**Comment by fritz-playmaker** [comment]
@alaindixon I stopped using the library and started using Sembast DB which offers better performance and no read and write errors. [](https://pub.dartlang.org/packages/sembast)

**Comment by alaindixon** [comment]
I have moved for Sembast, it's far better, thank you ;)

**Comment by marioreggiori** [comment]
Can you show me the code which leads to this error?

**Comment by fritz-playmaker** [comment]
```
 Future deleteCapturedData(String projectId) async {
     Directory appDocDir = await getApplicationDocumentsDirectory();
    String dbFilePath = appDocDir.path + "/op_" + projectId + ".data";
    var db = ObjectDB(dbFilePath);
    db.open();
    await db.remove({});
    await db.close();
  }
```

**Comment by DevilWarrior** [comment]
@marioreggiori 

I think the issue is found at `objectdb_base.dart` around line 95. It tries to remove the .bak file but for some reason (I guess a separate bug) it doesn't exist. A quick workaround this is to check weather or not the backup file exist before removing it:

`if (await backupFile.exists()) await backupFile.delete();`

**Comment by DevilWarrior** [comment]
> @marioreggiori
> 
> I think the issue is found at `objectdb_base.dart` around line 95. It tries to remove the .bak file but for some reason (I guess a separate bug) it doesn't exist. A quick workaround this is to check weather or not the backup file exist before removing it:
> 
> `if (await backupFile.exists()) await backupFile.delete();`

Never mind, the issue still persist after the change above ;(

**Comment by GleidsonRamos** [comment]
Put false inside db.open(). Like this:

`db.open(false);`

It's the parameter "tidy up".
Should resolve.
