### ISSUE TITLE
Update function no change data when reopen app

### ISSUE THREAD

**Issue by SuperSonicLLC** [marioreggiori/objectdb#26]
When I update a record in db and then i see in log, record are updated with new data. But when i reopen App, data in record no change after update method. Anyone have idea for fix that ?

**Comment by marioreggiori** [comment]
Can you show the code where you open/update/close the db?

**Comment by SuperSonicLLC** [comment]
Open DB
```
  Future<ObjectDB> _initDb() async {
    // get document directory using path_provider plugin
    Directory appDocDir = await getApplicationDocumentsDirectory();
    String dbFilePath = [appDocDir.path, 'carpro.db'].join('/');

    // delete old database file if exists
    File dbFile = File(dbFilePath);
    // check if database already exists
    var isNew = !await dbFile.exists();
    // initialize and open database
    ObjectDB db = ObjectDB(dbFilePath);
    db.open();

    return db;
  }
```
Close db 
```
  void closeDb() async {
    var db = await getDb();
    db.close();
  }
```
And Update DB
```
  Future updateTransaction(TransactionData transaction) async {
    var dbClient = await _db.getDb();
    await dbClient.update({
      ManagerData.ID_KEY: transaction.transactionId,
      ManagerData.TABLE_KEY: ManagerData.TRANSACRIONS_TABLE
    }, transaction.toMap());
    print("Transactions updated: ${transaction.toMap()}");
  }
```

**Comment by marioreggiori** [comment]
Try calling db.close() with await.
Otherwise the db isn't getting closed properly since it's async.

**Comment by SuperSonicLLC** [comment]
I tried db.close() with await but that issue still occur !

**Comment by ajplumlee33** [comment]
It looks like only the insert methods immediately write the changes to the db file.  But the tidy() method will do that for you.  Use it after each update and your problem should be resolved:

`Future<ObjectDB> _tidy() async {
    await this._writer.close();
    await this._file.rename(this.path + '.bak');
    this._file = File(this.path);
    IOSink writer = this._file.openWrite();
    writer.writeln('\$objectdb' + this._meta.toString());
    writer.writeAll(this._data.map((data) => json.encode(data)), '\n');
    writer.write('\n');
    await writer.flush();
    await writer.close();

    var backupFile = File(this.path + '.bak');
    await backupFile.delete();

    return await this._open(false);
  }`
