### ISSUE TITLE
ObjectDB exception

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [marioreggiori/objectdb#30]
When I update or insert sometimes I am getting "data contains invalid data types":
      

    ObjectId _insert(data) {
       ObjectId _id = ObjectId();
        data['_id'] = _id.toString();
        try {
          this._writer.writeln('+' + json.encode(data));
          this._insertData(data);
        } catch (e) {
         throw ObjectDBException('data contains invalid data types');
        }
        return _id;
      }

e.message is "StreamSink is closed"

**Comment by marioreggiori** [comment]
Can you add the data you want to insert?

**Comment by marioreggiori** [comment]
Please reopen and provide some data if this still happens.
