### ISSUE TITLE
Find by property not null

### ISSUE THREAD

**Issue by lequanghiep74** [marioreggiori/objectdb#31]
I find first element with property not null but it not working. Please help me to query it.
`
a.first( {
    Op.not: {'units': null}
 });
`

**Comment by marioreggiori** [comment]
Is the value really `null` or "not set"?

**Comment by ali-1989** [comment]
use this:

`a.first( {'units':  RegExp(r'.*'),  Op.not: {'units': null} });`    means: where 'units' exist and is not null.

`a.first( {Op.not: {'units': null} });`         means: where 'units' exist and is not null OR 'units' is not defined.
