### ISSUE TITLE
[Features] Text search

### ISSUE THREAD

**Issue by emce** [marioreggiori/objectdb#62]
**Is your feature request related to a problem? Please describe.**
I need possibility to filter data by text serch

**Describe the solution you'd like**
Text search methods like startsWith, endsWith, contains, etc
**Describe alternatives you've considered**
One can use collections alternatives, but native mechanism would be better.

**Comment by marioreggiori** [comment]
You can use regex to search text

Example:
https://github.com/marioreggiori/objectdb/blob/main/example/lib/main.dart#L57
