### ISSUE TITLE
Are queries available in the current release?

### ISSUE THREAD

**Issue by jonny7737** [marioreggiori/objectdb#64]
`{"2021-05-23 06:22:10.149196":{"symbol":"mvis","action":"bought","quantity":0.0,"cost":20.5,"watch":true},"_id":"60aa3ae2e723bbff6862ae69"}
{"2021-05-23 06:22:10.154262":{"symbol":"gbtc","action":"bought","quantity":0.0,"cost":52.96,"watch":true},"_id":"60aa3ae2e723bbff6862ae6a"}
{"2021-05-23 06:22:10.155244":{"symbol":"gme","action":"bought","quantity":0.0,"cost":79.88,"watch":true},"_id":"60aa3ae2e723bbff6862ae6b"}
{"2021-05-23 06:22:10.155363":{"symbol":"amc","action":"bought","quantity":0.0,"cost":16.5,"watch":true},"_id":"60aa3ae2e723bbff6862ae6c"}
{"2021-05-23 06:22:10.155430":{"symbol":"msft","action":"bought","quantity":0.0,"cost":250.0,"watch":true},"_id":"60aa3ae2e723bbff6862ae6d"}
`

find() returns all documents as expected.
find({'watch': true}) returns an empty list.
first({'watch': true}) returns no documents.
last({'watch': true}) returns no docments.

first and last with query result in a Bad State exception in dart Stream somewhere.

Is is the structure of my documents causing this issue?

**Comment by marioreggiori** [comment]
You need to provide the full 'key-path' in your query. You should change the structure so that the keys you want to query are not dynamic/unknown.

The exception is expected for first and last if no record was found.
