### ISSUE TITLE
Invalid Argument in _encodeValue()

### ISSUE THREAD

**Issue by mikes222** [marioreggiori/objectdb#65]
**Describe the bug**

When doing an `update` the system responds with `ArgumentError` in `_encodeValue()` in `objectdb_storage_filesystem.dart`. Since the structure is big I do not have any hint which type cannot be encoded here. Therefore I ask to give more information in the exception. For example the type of the value. 

**To Reproduce**

**Expected behavior**
An exception stating what type cannot be encoded.

**Screenshots**

**Desktop (please complete the following information):**
 - Dart Version 2.12 with `// @dart=2.9` in the first line of main.dart

**Comment by marioreggiori** [comment]
Only valid json values may be inserted into ObjectDB. Other values can be inserted by encoding them to a valid json value using the SchemaDB constructor. Check out the [example](https://github.com/marioreggiori/objectdb/blob/main/example/lib/main.dart#L36)

**Comment by marioreggiori** [comment]
I will look into more detailed exceptions

**Comment by mikes222** [comment]
Thx for making the app more verbose. According to #63 I assume that updating with `null` fails for me too. Not yet tested though but the lib worked like a charm before upgraded to nullSafety and the content of the database had not changed.
